### ISSUE TITLE
新闻页面出错，没有内容。

### ISSUE THREAD

**Issue by laucherish** [oubowu/OuNews#2]
提示
UNIQUE constraint failed:
NEWS_CHANNEL_TABLE.NEWS_CHANNEL

**Comment by oubowu** [comment]
能把具体的操作步骤告诉我吗？之前也有人跟我说过这个问题。我猜是这里的问题：INewsInteractorImpl的第43行，第一次进入时去SpUtil.readBoolean("initDb")为false，把数据插入进去了，但是出了什么意外导致60行 SpUtil.writeBoolean("initDb", true)没有执行,然后再此进入又把数据插入数据库，然后 newsChannelName 不唯一了就报那个错误

**Comment by laucherish** [comment]
就是把你的项目clone到本地之后，用Android Studio导入，运行之后就报这个错误。
应该就是你发现的那个问题，清除应用数据之后就没问题了。

**Comment by oubowu** [comment]
坑爹啊，我把app卸载后，将项目下载下来导入运行没报错。而且NEWS_CHANNEL这个属性是不存在的，这个是我很久前定义的，Daogenerator已经改为 note.addStringProperty("newsChannelName").notNull().primaryKey().index();用newsChannelName坐主键了；报bug也应该是NEWS_CHANNEL_TABLE.NEWS_CHANNEL_NAME才对；实在是坑爹啊

**Comment by laucherish** [comment]
报的bug也应该是NEWS_CHANNEL_TABLE.NEWS_CHANNEL_NAME
只是在手机上不能显示完整，显示的是NEWS_CHANNEL_TABLE.NEWS_CHANNEL....
