### ISSUE TITLE
关于包的结构

### ISSUE THREAD

**Issue by Ztiany** [oubowu/OuNews#4]
看了你的包的结构，按模块分是很不错的，复合java的设计规范。
看了有的项目是把M，V，P先分开，单独写在各个模块中，你是的一个模块中包含所MVP。你觉得哪种会比较好，还是各有优点？

**Comment by oubowu** [comment]
个人感觉按模块好点，人家看起来也方便

**Comment by oubowu** [comment]
项小的时候不分，项目大一个模块有好几个页面的话就按模块分吧
