### ISSUE TITLE
leakcanary 在很多Activity里面都报oom

### ISSUE THREAD

**Issue by kakarrot** [oubowu/OuNews#5]
leakcanary在很多Activity里面都报oom
![mmexport1459934103386](https://cloud.githubusercontent.com/assets/5986919/14311687/34352ee6-fc1b-11e5-87d6-401f5653aef3.jpg)

**Comment by oubowu** [comment]
啥系统 啥机子 点开某个让我看看具体的问题描述

**Comment by kakarrot** [comment]
我的机器上面都有报的，红米Note ，华为mate8

![4ccdbaad0142fb8a7d0e7b799252a938](https://cloud.githubusercontent.com/assets/5986919/14372461/7710c6e0-fd73-11e5-85a0-32c72f97e2f9.jpg)
![587125d3de01913d3865efd75654e43c](https://cloud.githubusercontent.com/assets/5986919/14372468/7f39a97c-fd73-11e5-81ba-f2e3b7d2a219.jpg)

![de778a4b1995f2eac69e6f2fc20f3dba](https://cloud.githubusercontent.com/assets/5986919/14372473/85c1abbe-fd73-11e5-9681-5ca12c7d5e2c.jpg)

基本上多点几下，滑动几下就弹出来了

**Comment by oubowu** [comment]
搜了下 感觉是LeakCanary的bug 凯子哥有说：http://bbs.csdn.net/topics/391842590

**Comment by kakarrot** [comment]
嗯，貌似如此，项目感觉很不错，只是感觉图片加载可以再封装一层，便于替换，mvp那块不知道是不是因为你使用了RxJava的原因，感觉看起来有点复杂，下面这个项目是我在别处看到的mvp的实现（https://github.com/liuguangqiang/shuba），也不是说比你的好，只是逻辑上易于理解一点，类也没有那么多，mvp开发我也在学习中，可能说得不准确，希望能多交流

**Comment by oubowu** [comment]
Rxjava看起来复杂 用熟了看上去逻辑会很清晰的

**Comment by kakarrot** [comment]
另外还有部分手机显示问题，如图：
![image](https://cloud.githubusercontent.com/assets/5986919/14372888/51bb06e0-fd77-11e5-894f-82e00a988244.png)

以及详情页面不显示时间状态栏。
![screenshot_2016-04-08-10-42-26_com oushangfeng ou](https://cloud.githubusercontent.com/assets/5986919/14372922/a2492326-fd77-11e5-9a5f-efabeb614afc.png)

在华为mate8上没有这个问题，在红米Note 4.4.4的系统上有这个问题

**Comment by oubowu** [comment]
做沉浸状态栏最坑爹就是定制系统了 新闻详情没时间状态栏是为了4.4适配沉浸状态栏我设全屏的 你可以看到拉动时候toolbar其实是跟随动的

**Comment by kakarrot** [comment]
嗯， 安卓适配确实伤脑筋，我看你自己写的注入，不知道为什么没考虑使用butterknife 或者 dagger 呢？

**Comment by oubowu** [comment]
原因很简单 自己想练习一下注入 dagger是还没用过 所以没用到

**Comment by kakarrot** [comment]
嗯，看了你代码，觉得你很牛，从你代码中也能学到很多东西，用到的技术也是比较新的，欢迎大牛继续分享好的东西

**Comment by oubowu** [comment]
还好吧 还不能造轮子啊

**Comment by oubowu** [comment]
刚刚刷了个MIUI知道你说的问题了，是不是首页推上去然后Toolbar没被状态栏遮住，这个是没办法的，4.4的特性就这样，5.0以上机子就可以遮住，为了实现那个布局延伸到状态栏4.4也只能这样做了，这是我能想到的最好的方案了

**Comment by oubowu** [comment]
已经更新代码，现在是4.4系统我回去监听AppbarLayout的偏移量，它的偏移量其实就是Toolbar的高度，然后根据偏移量设置Toolbar的透明度，这样子推上去的时候就不会跟状态栏重叠了，你可以更新下代码看看咯

**Comment by oubowu** [comment]
详情页面不显示时间状态栏的问题已经找到解决方法，方法是设置flag使得Activity全屏的布局不会被状态栏让出位置，再显示状态栏，然后Toolbar设置marginTop为状态栏高度，和5.0系统的折叠Layout效果一毛一样了，可以试下
