### ISSUE TITLE
怎么编译呢出现了Failed to resolve

### ISSUE THREAD

**Issue by YLBFDEV** [oubowu/OuNews#7]
Failed to resolve: tv.danmaku.ijk.media……

**Comment by oubowu** [comment]
可能是网络问题？这些依赖库都是ijkplayer的依赖 一般AS需要翻墙才能把依赖下载下来

**Comment by YLBFDEV** [comment]
我找到问题了 jcenter上还没有编译出0.6.2的版本 换成0.6.1了
