### ISSUE TITLE
求教如何在baseadadpter里面添加头部呢?

### ISSUE THREAD

**Issue by jaysowen** [oubowu/OuNews#8]
如题,很想改造一下,添加头部banner,但是发现这个adapter好像扩展性有限.想请教如何添加header,感谢

**Comment by oubowu** [comment]
无非就是多一个banner的type，然后在外面填充view（adapter.setHeader (view)）的时候parent是recyclerview，还要在adapter设置一个参数处理一下多了个头部的数据的偏移量

**Comment by jaysowen** [comment]
好的,多谢指导
