### ISSUE TITLE
哥们,能给我介绍下缓存的规则吗?

### ISSUE THREAD

**Issue by m122469119** [oubowu/OuNews#9]
如题,谢,retrofit有更好的缓存方案吗??

**Comment by oubowu** [comment]
看下这篇文章：http://www.jianshu.com/p/9c3b4ea108a7，
然后说明下只有get才能缓存，post不能，你可以借助第三方缓存库比如RxCache来实现

**Comment by oubowu** [comment]
@m122469119

**Comment by m122469119** [comment]
.....就拿你这个项目来说吧,
第一次发起网络请求,如果有网缓存两分钟?
第二次发起网络请求,如果断网,将之前的缓存重新缓存2天?
第三次发起网络请求,如果有网,设置新的缓存重新缓存2分钟?

**Comment by oubowu** [comment]
刚看完欧冠，同时经过试验可以给你一个答复了，每次请求都会设置请求头缓存策略去缓存最新的数据，因为怕响应头没有处理缓存，所以我们需要一个拦截器将缓存策略加到响应头。
      然后我的缓存策略是：
      1.有网时，设置Cache-Control: max-age=0，max-age=0，就是指定在0时刻内给我返回缓存，因为0时刻返回不了，所以会去请求数据；如果是max-age=30的话，就是在我请求到数据那一次开始算起，30秒内调同样的接口它直接读缓存，30秒后又去请求数据，周而复始。
      2.没网时，设置Cache-Control: max-stale=60 * 60 * 24 * 2（两天）, only-if-cached，就是只读缓存，并且缓存有效时间是2天（从第一次无网读缓存算起），2天后读取的时候会报 504 Unsatisfiable Request (only-if-cached)，因为缓存失效了。
     按照你的说法，第一次发起网络请求，如果有网的话请求数据，缓存数据，没有无效时间；第二次发起网络请求，如果断网，就去读取缓存，有效时间2天；第三次发起网络请求数据，缓存数据；如果断网再去请求数据，读缓存，并且又是从这一次开始算起。这样子应该能明白了吧？？？
      我的代码有些错误，待我改好再通知你更新下，网上的教程有点坑，被带入坑了。还是得自己动手测才知道具体结果！！！

**Comment by oubowu** [comment]
@m122469119

**Comment by oubowu** [comment]
搞定了，修正了缓存的bug，然后现在统一在拦截器配置请求头和响应头的缓存策略，省得每个接口都加 @m122469119

**Comment by m122469119** [comment]
谢谢...
